runtime: nodejs18

env_variables:
  REACT_APP_BE_URL: "http://34.83.186.103"
  NODE_OPTIONS: "--openssl-legacy-provider"

handlers:
  - url: /static
    static_dir: build/static/
  - url: /
    static_files: build/index.html
    upload: build/index.html
