runtime: nodejs18

env_variables:
  REACT_APP_BE_URL: "https://billersmindbackend-337780895889.us-central1.run.app"
  NODE_OPTIONS: "--openssl-legacy-provider"

handlers:
  - url: /static
    static_dir: build/static/
  - url: /
    static_files: build/index.html
    upload: build/index.html
